### ISSUE TITLE
ImportError: No module named 'ss2'

### ISSUE THREAD

**Issue by saurumesh** [inside-openflow/simpleswitch2#1]
I cloned repo, and tried to use start the SS2 Core application as described in README.md, but it doesn't work. Could you please help to understand if I am taking it wrong.
Below is the error I'm getting

ist@ist:~/Downloads/software/simpleswitch2-0.1.2-noacl$ ryu-manager ss2.core 
loading app ss2.core
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 11, in <module>
    load_entry_point('ryu==4.28', 'console_scripts', 'ryu-manager')()
  File "/usr/local/lib/python3.5/dist-packages/ryu/cmd/manager.py", line 98, in main
    app_mgr.load_apps(app_lists)
  File "/usr/local/lib/python3.5/dist-packages/ryu/base/app_manager.py", line 415, in load_apps
    cls = self.load_app(app_cls_name)
  File "/usr/local/lib/python3.5/dist-packages/ryu/base/app_manager.py", line 392, in load_app
    mod = utils.import_module(name)
  File "/usr/local/lib/python3.5/dist-packages/ryu/utils.py", line 108, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked

$ mn --version
2.3.0d4

$ ryu --version
ryu 4.28

**Comment by leonexis** [comment]
The current directory may not be in the `PYTHON_PATH`. Try the following:

```
$ PYTHON_PATH=".:$PYTHON_PATH" ryu-manager ss2.core
```
